// generated by stringer -type ResourceType resource.go; DO NOT EDIT

package database

import "fmt"

const _ResourceType_name = "DirectoryFileUrl"

var _ResourceType_index = [...]uint8{0, 9, 13, 16}

func (i ResourceType) String() string {
	if i < 0 || i+1 >= ResourceType(len(_ResourceType_index)) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
